### ISSUE TITLE
Embed command only sends the first part of the given argument

### ISSUE THREAD

**Issue by Wizzable** [FusionSid/Why-Bot#27]

**Comment by FusionSid** [comment]
are you talking about the ?embed command 
If so:
If you are adding more that one word you wrap the text in quotes, example:

?embed --title "Hello world" --desc "This is a test message" --color blue

**Comment by Wizzable** [comment]
Ahh ok that makes more sense that you

**Comment by FusionSid** [comment]
no problem :)
