### ISSUE TITLE
Is the rewrite branch ready for testing?

### ISSUE THREAD

**Issue by amantu-qbit** [FusionSid/Why-Bot#28]

**Comment by FusionSid** [comment]
Kinda,
I plan on rewriting the bot and this is the branch. Most of the commands/systems will be changed and even though I will use some code from the master branch I will try to rewrite that too.  Also I need to switch all my db from json (which is not good) to sql. I haven't really gotten time recently to work on the both though.

**Comment by amantu-qbit** [comment]
@FusionSid Can I import the bot to server and Run?

**Comment by FusionSid** [comment]
the rewrite branch? yes. Just run setup.py first to make the db's and cd into src before running

**Comment by amantu-qbit** [comment]
![image](https://user-images.githubusercontent.com/67361813/172760524-8ee75d0d-e51f-49c4-8889-5f883f52ae58.png)
Running into this issue

**Comment by amantu-qbit** [comment]
Sorry Just Realized using old python. Fixed after upgraded to 3.9

**Comment by FusionSid** [comment]
lol ok, so is it working fine now?
